FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ./*.sln ./
COPY ./*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p ./${file%.*}/ && mv $file ./${file%.*}/; done
RUN dotnet restore ./WebApplication_1007.sln
COPY . .
RUN dotnet publish ./WebApplication_1007/WebApplication_1007.csproj -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /publish
COPY --from=build /publish .
ENV ASPNETCORE_URLS="http://*:5000"
EXPOSE 5000
ENTRYPOINT ["dotnet", "WebApplication_1007.dll"]